# -*- coding: utf-8 -*-
"""agent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Co2SVK08QiQGJzvfyw5CfUHLbEf5mR_C
"""

import time
import torch
import torchvision

model = torchvision.models.shufflenet_v2_x0_5(weights='IMAGENET1K_V1')
model.fc = torch.nn.Linear(model.fc.in_features, 18)
  
class BullyAgent_v2(torch.nn.Module):
  def __init__(self, device):
        super(BullyAgent_v2, self).__init__()
        self.my_model = model
        self.device = device
        self.softmax = torch.nn.Softmax()
        self.step = 0
  
  def __call__(self, state):
    state = state.to(self.device)
    image = state.permute(2,0,1)
    image = image / 255.
    image = torch.unsqueeze(image[:, 30:-30,30:-30], dim = 0)
    image = self.my_model(image)
    image = torch.flatten(image)
    return self.softmax(image) + 0.2/18

def load_module(model_path, device):
    agent = BullyAgent_v2(device)
    agent.load_state_dict(torch.load(model_path))
    agent.to(device)
    return agent